# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/inference.proto\x12\x03\x43\x41I\"u\n\x0cInferRequest\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x63hunk_id\x18\x02 \x01(\x05\x12\x12\n\nrequest_id\x18\x03 \x01(\t\x12\x14\n\x0ctensor_shape\x18\x04 \x03(\x05\x12\x14\n\x0ctensor_dtype\x18\x05 \x01(\t\"\x91\x01\n\rInferResponse\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x63hunk_id\x18\x02 \x01(\x05\x12\x12\n\nrequest_id\x18\x03 \x01(\t\x12\x14\n\x0ctensor_shape\x18\x04 \x03(\x05\x12\x14\n\x0ctensor_dtype\x18\x05 \x01(\t\x12\x19\n\x11inference_time_ms\x18\x06 \x01(\x02\"\x0f\n\rHealthRequest\"A\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x10\n\x08\x63hunk_id\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\"\x0e\n\x0cPauseRequest\"0\n\rPauseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\"(\n\x11\x43heckpointRequest\x12\x13\n\x0boutput_path\x18\x01 \x01(\t\"n\n\x12\x43heckpointResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0f\x63heckpoint_path\x18\x02 \x01(\t\x12\x12\n\nsize_bytes\x18\x03 \x01(\x03\x12\x1a\n\x12\x63heckpoint_time_ms\x18\x04 \x01(\x02\"(\n\rResumeRequest\x12\x17\n\x0f\x63heckpoint_path\x18\x01 \x01(\t\"1\n\x0eResumeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t2\x9c\x02\n\x10InferenceService\x12.\n\x05Infer\x12\x11.CAI.InferRequest\x1a\x12.CAI.InferResponse\x12\x36\n\x0bHealthCheck\x12\x12.CAI.HealthRequest\x1a\x13.CAI.HealthResponse\x12.\n\x05Pause\x12\x11.CAI.PauseRequest\x1a\x12.CAI.PauseResponse\x12=\n\nCheckpoint\x12\x16.CAI.CheckpointRequest\x1a\x17.CAI.CheckpointResponse\x12\x31\n\x06Resume\x12\x12.CAI.ResumeRequest\x1a\x13.CAI.ResumeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERREQUEST']._serialized_start=30
  _globals['_INFERREQUEST']._serialized_end=147
  _globals['_INFERRESPONSE']._serialized_start=150
  _globals['_INFERRESPONSE']._serialized_end=295
  _globals['_HEALTHREQUEST']._serialized_start=297
  _globals['_HEALTHREQUEST']._serialized_end=312
  _globals['_HEALTHRESPONSE']._serialized_start=314
  _globals['_HEALTHRESPONSE']._serialized_end=379
  _globals['_PAUSEREQUEST']._serialized_start=381
  _globals['_PAUSEREQUEST']._serialized_end=395
  _globals['_PAUSERESPONSE']._serialized_start=397
  _globals['_PAUSERESPONSE']._serialized_end=445
  _globals['_CHECKPOINTREQUEST']._serialized_start=447
  _globals['_CHECKPOINTREQUEST']._serialized_end=487
  _globals['_CHECKPOINTRESPONSE']._serialized_start=489
  _globals['_CHECKPOINTRESPONSE']._serialized_end=599
  _globals['_RESUMEREQUEST']._serialized_start=601
  _globals['_RESUMEREQUEST']._serialized_end=641
  _globals['_RESUMERESPONSE']._serialized_start=643
  _globals['_RESUMERESPONSE']._serialized_end=692
  _globals['_INFERENCESERVICE']._serialized_start=695
  _globals['_INFERENCESERVICE']._serialized_end=979
# @@protoc_insertion_point(module_scope)
